language: node_js
node_js:
  - "5"
  - "5.1"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - CXX=g++-4.8
before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -q
  - sudo apt-get -y --force-yes install rethinkdb
  - bash dependencies.sh
before_script:
  - npm install -g gulp
  - gulp
  - rethinkdb --daemon
  - node ./db/migrate -e test
  - node ./db/seed -e test
  - node ./dist/server -e test &