language: node_js
node_js:
  - "5"
  - "5.1"
before_script:
  - npm install -g gulp
  - gulp
  - sudo add-apt-repository ppa:rethinkdb/ppa && sudo apt-get update && sudo apt-get install rethinkdb
  - node ./db/migrate -e test
  - node ./dist/server -e test &